-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 11:01:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET latin1 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`permiso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `slug` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`permiso_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`permiso_rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol_id` INT NULL,
  `permiso_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `per_idx` (`permiso_id` ASC),
  INDEX `rolid_idx` (`rol_id` ASC),
  CONSTRAINT `permisoid`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `biblioteca`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rolid`
    FOREIGN KEY (`rol_id`)
    REFERENCES `biblioteca`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL,
  `password` VARCHAR(100) NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario_rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol_id` INT NULL,
  `usuario_id` INT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `xx_idx` (`usuario_id` ASC),
  INDEX `rolid_idx` (`rol_id` ASC),
  CONSTRAINT `usuarioid`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `biblioteca`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rolid`
    FOREIGN KEY (`rol_id`)
    REFERENCES `biblioteca`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `isbn` VARCHAR(30) NULL,
  `autor` VARCHAR(100) NULL,
  `cantidad` TINYINT(2) NULL,
  `editorial` VARCHAR(50) NULL,
  `foto` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro_prestamo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `libro_id` INT NULL,
  `fecha_prestamo` DATE NULL,
  `prestado_a` VARCHAR(100) NULL,
  `estado` TINYINT(1) NULL,
  `fecha_devolucion` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `usuarioid_idx` (`usuario_id` ASC),
  INDEX `libroid_idx` (`libro_id` ASC),
  CONSTRAINT `usuarioid`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `biblioteca`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `libroid`
    FOREIGN KEY (`libro_id`)
    REFERENCES `biblioteca`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
